# -*- coding: utf-8 -*-
"""fake.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vH1qCgbj9nL_FWBKmySzmdytNZgSGeEe
"""

print ("It's working!")